#Common vars
availability_zone : melbourne-qh2-uom
instance_image : 356ff1ed-5960-4ac2-96a1-0c0198e6a999
instance_flavor : uom.mse.2c9g
instance_key_name : slave1samy

#Volume
volumes:
  - vol_name: master-volume
    vol_size: 100
  - vol_name: slave1-volume
    vol_size: 100
  - vol_name: slave2-volume
    vol_size: 100
  
#Security groups
security_groups:
  - name: demo_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22 
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "Demo scurity group for HTTP"
    protocol: tcp
    port_range_min: 80 
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

#Instance
instances:
  - name: Masternode
    volumes: ['master-volume']
  - name: slave1
    volumes: [slave1-volume]
  - name: slave2
    volumes: [slave2-volume]